version: '3'

services:
  server:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    #command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - PHP_EXTENSION_XDEBUG=1
  web:
    image: nginx:1.17-alpine
    depends_on:
      - server
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    volumes:
      - wacomi_db:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
volumes:
  wacomi_db:

      